/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sanctum/csrf-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Initialize Sanctum CSRF cookie
         * @description Call this once before any authenticated request. Server sets the
         *     `XSRF-TOKEN` cookie. Client must echo it in `X-XSRF-TOKEN` header
         *     on all subsequent POST/PUT/PATCH/DELETE requests.
         */
        get: operations["getCsrfCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user (email + password)
         * @description Creates a user record and dispatches a verification email.
         *     The account is unusable until the verification link is clicked.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verify/{id}/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify the user's email via signed link */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verification-notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend the verification email */
        post: operations["resendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin Google OAuth flow */
        get: operations["googleOauthRedirect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: operations["googleOauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset email */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password using a reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's profile */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/user/email/change-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request an email-change verification email */
        post: operations["requestEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the current user's password */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/api/user/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the current user account (14-day grace) */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's children */
        get: operations["listChildren"];
        put?: never;
        /** Add a child record */
        post: operations["createChild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/children/{childId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                childId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a child record */
        delete: operations["deleteChild"];
        options?: never;
        head?: never;
        /** Update a child record */
        patch: operations["updateChild"];
        trace?: never;
    };
    "/api/sekolah": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sekolah facilities (hierarchical filter)
         * @description Mirrors the public URL hierarchy. Supply only the levels that apply.
         *     Sort is fixed: score DESC, name ASC. 50 items per page.
         */
        get: operations["listSekolah"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sekolah/{provinsi}/{kabkota}/{kecamatan}/{school_type}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Sekolah detail */
        get: operations["getSekolahDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universitas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Universitas facilities */
        get: operations["listUniversitas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universitas/{provinsi}/{kabkota}/{kecamatan}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Universitas detail */
        get: operations["getUniversitasDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kursus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kursus facilities (with category filter)
         * @description Includes facilities whose `main_category_slug` matches OR whose
         *     sub-categories include the slug. Timedoor facilities are pinned-top
         *     when present.
         */
        get: operations["listKursus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kursus/{provinsi}/{kabkota}/{kecamatan}/{main_category}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Kursus detail */
        get: operations["getKursusDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sekolah/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyword search within Sekolah */
        get: operations["searchSekolah"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universitas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyword search within Universitas */
        get: operations["searchUniversitas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kursus/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyword search within Kursus (Timedoor pinned-top) */
        get: operations["searchKursus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facilities/{facilityId}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add facility to favorites (one-way, cumulative) */
        post: operations["addFavorite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my favorites */
        get: operations["listMyFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facilities/{facilityId}/inquiries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an inquiry to a facility
         * @description Rate-limited to 1 per (user, facility) per rolling hour.
         *     Email is dispatched with `Reply-To` set to the user's address.
         */
        post: operations["submitInquiry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facilities/{facilityId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a star rating (one-time, no re-rating) */
        post: operations["submitReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facilities/{facilityId}/my-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        /** Get the current user's review for a facility (if any) */
        get: operations["getMyReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/rekomendasi/sekolah": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 8 random Sekolah facilities (score >= 10) */
        get: operations["getSekolahRekomendasi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/rekomendasi/universitas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 8 random Universitas facilities (score >= 10) */
        get: operations["getUniversitasRekomendasi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home/rekomendasi/kursus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 8 Kursus cards (2 Timedoor + 6 general, randomized) */
        get: operations["getKursusRekomendasi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all provinces */
        get: operations["listProvinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/kabkota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List kabupaten/kota in a province */
        get: operations["listKabkota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regions/kecamatan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List kecamatan in a kabkota */
        get: operations["listKecamatan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kursus-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active kursus categories */
        get: operations["listKursusCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/registration-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a new-listing request (public, requires Turnstile) */
        post: operations["submitRegistrationRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/correction-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an information-correction request */
        post: operations["submitCorrectionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/deletion-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a removal request for a facility */
        post: operations["submitDeletionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/sendgrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SendGrid event webhook (delivered / bounced / dropped)
         * @description Verified via the `X-Twilio-Email-Event-Webhook-Signature` header.
         *     Payload is an array of SendGrid event objects; outcomes are written
         *     to `mail_logs.status`.
         */
        post: operations["sendgridWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/revalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Next.js ISR revalidation (Laravel → Next.js)
         * @description Called by Laravel after any score- or status-affecting write.
         *     Authenticated by a shared `X-Revalidate-Secret` header.
         */
        post: operations["nextjsRevalidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example Resource not found. */
            message: string;
            /** @example NOT_FOUND */
            code?: string;
        };
        ValidationErrorResponse: {
            /** @example The given data was invalid. */
            message: string;
            /**
             * @example {
             *       "email": [
             *         "The email field is required."
             *       ],
             *       "password": [
             *         "The password must be at least 8 characters."
             *       ]
             *     }
             */
            errors: {
                [key: string]: string[];
            };
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example ratna@example.com
             */
            email: string;
            /**
             * Format: password
             * @description ≥8 chars; must include uppercase, lowercase, and a symbol.
             * @example StrongPass!1
             */
            password: string;
            /**
             * Format: password
             * @example StrongPass!1
             */
            password_confirmation: string;
            /** @example Ratna Dewi */
            name: string;
            /**
             * @example female
             * @enum {string}
             */
            gender: "male" | "female";
            /**
             * Format: date
             * @example 1985-06-12
             */
            birthdate: string;
            /** @example +6281234567890 */
            phone: string;
            /** @example 17 */
            province_id: number;
            /** @example 217 */
            kabkota_id: number;
            /** @example 2 */
            children_count: number;
            children?: components["schemas"]["ChildInput"][];
            /** @example 0.AAAA-bbbb-cccc */
            turnstile_token: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example ratna@example.com
             */
            email: string;
            /**
             * Format: password
             * @example StrongPass!1
             */
            password: string;
            turnstile_token?: string;
        };
        ProfileUpdateRequest: {
            name?: string;
            /** @enum {string} */
            gender?: "male" | "female";
            /** Format: date */
            birthdate?: string;
            phone?: string;
            province_id?: number;
            kabkota_id?: number;
        };
        User: {
            /** @example 12 */
            id?: number;
            /**
             * Format: email
             * @example ratna@example.com
             */
            email?: string;
            /** @example Ratna Dewi */
            name?: string;
            /**
             * @example female
             * @enum {string}
             */
            gender?: "male" | "female";
            /**
             * Format: date
             * @example 1985-06-12
             */
            birthdate?: string;
            /** @example +6281234567890 */
            phone?: string;
            /** @example 17 */
            province_id?: number;
            /** @example 217 */
            kabkota_id?: number;
            /** Format: date-time */
            email_verified_at?: string | null;
            children?: components["schemas"]["UserChild"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ChildInput: {
            /**
             * @example male
             * @enum {string}
             */
            gender: "male" | "female";
            /**
             * Format: date
             * @example 2014-09-21
             */
            birthdate: string;
        };
        UserChild: components["schemas"]["ChildInput"] & {
            /** @example 41 */
            id?: number;
            /** @example 12 */
            user_id?: number;
            /** Format: date-time */
            created_at?: string;
        };
        PaginationMeta: {
            /** @example 1 */
            current_page?: number;
            /** @example 50 */
            per_page?: number;
            /** @example 137 */
            total?: number;
            /** @example 3 */
            last_page?: number;
        };
        PaginatedFacilityCardList: {
            data?: components["schemas"]["FacilityCard"][];
            meta?: components["schemas"]["PaginationMeta"] & {
                /**
                 * @description True when zero results — frontend should emit `<meta robots=noindex>`.
                 * @example false
                 */
                noindex?: boolean;
            };
        };
        PaginatedFavoriteList: {
            data?: components["schemas"]["Favorite"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        /** @description Card-shape returned by list endpoints. Internal counters are NEVER included. */
        FacilityCard: {
            /** @example 8421 */
            id?: number;
            /**
             * @example sekolah
             * @enum {string}
             */
            category?: "sekolah" | "universitas" | "kursus";
            /** @example SMP Negeri 2 Kuta Utara */
            name?: string;
            /** @example smp-negeri-2-kuta-utara */
            slug?: string;
            /** @example Kab. Badung */
            kabkota_name?: string;
            /** Format: uri */
            image_main_url?: string | null;
            /** @example /sekolah/bali/kab-badung/kuta-utara/negeri/smp-negeri-2-kuta-utara */
            url?: string;
            /** @example false */
            is_timedoor_academy?: boolean;
        };
        FacilityBase: {
            id?: number;
            /** @enum {string} */
            category?: "sekolah" | "universitas" | "kursus";
            name?: string;
            slug?: string;
            description?: string | null;
            address?: string | null;
            /**
             * Format: double
             * @example -8.6705
             */
            latitude?: number | null;
            /**
             * Format: double
             * @example 115.2126
             */
            longitude?: number | null;
            province?: components["schemas"]["Province"];
            kabkota?: components["schemas"]["Kabkota"];
            kecamatan?: components["schemas"]["Kecamatan"];
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: uri */
            website?: string | null;
            /** Format: uri */
            image_main_url?: string | null;
            is_timedoor_academy?: boolean;
            /** @enum {string} */
            status?: "active" | "removed";
            /** Format: date-time */
            last_verified_at?: string | null;
        };
        SekolahDetail: components["schemas"]["FacilityBase"] & {
            /** @enum {string} */
            school_type?: "negeri" | "swasta" | "international";
            accreditation?: string | null;
            curriculum?: string | null;
            biaya?: string | null;
            jam_sekolah?: string | null;
            fasilitas?: string | null;
        };
        UniversitasDetail: components["schemas"]["FacilityBase"] & {
            /** @enum {string} */
            jenis?: "Universitas" | "S1" | "S2" | "S3" | "D1-D4";
            program_studi?: string | null;
            jalur_masuk?: string | null;
            biaya?: string | null;
            fasilitas?: string | null;
            faculties_text?: string | null;
            prodi_text?: string | null;
        };
        KursusDetail: components["schemas"]["FacilityBase"] & {
            main_category?: components["schemas"]["KursusCategory"];
            sub_categories?: components["schemas"]["KursusCategory"][];
            program?: string | null;
            usia?: string | null;
            jadwal?: string | null;
            biaya?: string | null;
            fasilitas?: string | null;
        };
        Favorite: {
            id?: number;
            facility?: components["schemas"]["FacilityCard"];
            /** Format: date-time */
            created_at?: string;
        };
        InquiryRequest: {
            /** @example Pertanyaan tentang biaya pendaftaran */
            subject: string;
            /** @example Selamat siang, saya ingin bertanya tentang biaya pendaftaran tahun ajaran 2026... */
            message: string;
            turnstile_token: string;
        };
        Inquiry: {
            id?: number;
            facility_id?: number;
            subject?: string;
            message?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ReviewRequest: {
            /** @example 4 */
            rating: number;
            turnstile_token: string;
        };
        Review: {
            id?: number;
            facility_id?: number;
            rating?: number;
            /** Format: date-time */
            created_at?: string;
        };
        Province: {
            /** @example 17 */
            id?: number;
            /** @example Bali */
            name?: string;
            /** @example bali */
            slug?: string;
        };
        Kabkota: {
            /** @example 217 */
            id?: number;
            /** @example 17 */
            province_id?: number;
            /** @example Kabupaten Badung */
            name?: string;
            /** @example kab-badung */
            slug?: string;
            /**
             * @example kabupaten
             * @enum {string}
             */
            type?: "kabupaten" | "kota";
        };
        Kecamatan: {
            /** @example 1402 */
            id?: number;
            /** @example 217 */
            kabkota_id?: number;
            /** @example Kuta Utara */
            name?: string;
            /** @example kuta-utara */
            slug?: string;
        };
        KursusCategory: {
            /** @example 4 */
            id?: number;
            /** @example Coding */
            name?: string;
            /** @example coding */
            slug?: string;
            /** @example true */
            is_active?: boolean;
        };
        RegistrationRequest: {
            facility_name: string;
            /** @enum {string} */
            category: "sekolah" | "universitas" | "kursus";
            province_id: number;
            kabkota_id: number;
            kecamatan_id: number;
            address?: string;
            /** Format: uri */
            website?: string | null;
            phone?: string | null;
            requester_name: string;
            /** Format: email */
            requester_email: string;
            message: string;
            turnstile_token: string;
        };
        CorrectionRequest: {
            /** Format: uri */
            facility_url: string;
            requester_name: string;
            /** Format: email */
            requester_email: string;
            message: string;
            turnstile_token: string;
        };
        DeletionRequest: {
            /** Format: uri */
            facility_url: string;
            requester_name: string;
            /** Format: email */
            requester_email: string;
            reason: string;
            turnstile_token: string;
        };
    };
    responses: {
        /** @description Authentication required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Facility has been removed (soft-deleted). */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 1-based page number. Page size is fixed at 50. */
        Page: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrfCookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF cookie issued. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration accepted; verification email queued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful; session cookie set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email not yet verified. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many login attempts. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                id: number;
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified — redirects to frontend. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Verification link expired. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification email queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Too many requests. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleOauthRedirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google's consent screen. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleOauthCallback: {
        parameters: {
            query: {
                code: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logs the user in and redirects to frontend. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example ratna@example.com
                     */
                    email: string;
                    /** @example 0.AAA... */
                    turnstile_token: string;
                };
            };
        };
        responses: {
            /** @description If the email exists, a reset link has been sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: email */
                    email: string;
                    /** @description ≥8 chars, must include upper, lower, and a symbol. */
                    password: string;
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    requestEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    new_email: string;
                    /** Format: password */
                    current_password: string;
                };
            };
        };
        responses: {
            /** @description Verification email queued to new address. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    current_password: string;
                    /** Format: password */
                    password: string;
                    /** Format: password */
                    password_confirmation: string;
                };
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    current_password: string;
                };
            };
        };
        responses: {
            /** @description Account scheduled for deletion in 14 days. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listChildren: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Children list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserChild"][];
                };
            };
        };
    };
    createChild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildInput"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserChild"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    deleteChild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                childId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateChild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                childId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildInput"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserChild"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSekolah: {
        parameters: {
            query?: {
                provinsi?: string;
                kabkota?: string;
                kecamatan?: string;
                school_type?: "negeri" | "swasta" | "international";
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated Sekolah list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    getSekolahDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provinsi: string;
                kabkota: string;
                kecamatan: string;
                school_type: "negeri" | "swasta" | "international";
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sekolah detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SekolahDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    listUniversitas: {
        parameters: {
            query?: {
                provinsi?: string;
                kabkota?: string;
                kecamatan?: string;
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    getUniversitasDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provinsi: string;
                kabkota: string;
                kecamatan: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Universitas detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniversitasDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    listKursus: {
        parameters: {
            query?: {
                provinsi?: string;
                kabkota?: string;
                kecamatan?: string;
                category?: string;
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list (Timedoor first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    getKursusDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provinsi: string;
                kabkota: string;
                kecamatan: string;
                main_category: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kursus detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KursusDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    searchSekolah: {
        parameters: {
            query: {
                /** @example smp negeri kuta */
                q: string;
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    searchUniversitas: {
        parameters: {
            query: {
                q: string;
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    searchKursus: {
        parameters: {
            query: {
                q: string;
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFacilityCardList"];
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite added (or already existed — idempotent). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
        };
    };
    listMyFavorites: {
        parameters: {
            query?: {
                /** @description 1-based page number. Page size is fixed at 50. */
                page?: components["parameters"]["Page"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated favorites. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFavoriteList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    submitInquiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InquiryRequest"];
            };
        };
        responses: {
            /** @description Inquiry queued for delivery. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inquiry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
            /** @description Facility has no email or invalid input. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate-limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submitReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Review saved. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description User has already rated this facility. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            410: components["responses"]["Gone"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMyReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                facilityId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existing review or null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"] | null;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSekolahRekomendasi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Random 8 cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityCard"][];
                };
            };
        };
    };
    getUniversitasRekomendasi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Random 8 cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityCard"][];
                };
            };
        };
    };
    getKursusRekomendasi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2 Timedoor first, then 6 general (all randomized within group). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityCard"][];
                };
            };
        };
    };
    listProvinces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provinces. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Province"][];
                };
            };
        };
    };
    listKabkota: {
        parameters: {
            query: {
                provinsi_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kabkota list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kabkota"][];
                };
            };
        };
    };
    listKecamatan: {
        parameters: {
            query: {
                kabkota_slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kecamatan list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kecamatan"][];
                };
            };
        };
    };
    listKursusCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active kursus categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KursusCategory"][];
                };
            };
        };
    };
    submitRegistrationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrationRequest"];
            };
        };
        responses: {
            /** @description Request received; admin will review. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    submitCorrectionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionRequest"];
            };
        };
        responses: {
            /** @description Request received. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    submitDeletionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeletionRequest"];
            };
        };
        responses: {
            /** @description Request received; admin will review. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    sendgridWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Acknowledged. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    nextjsRevalidate: {
        parameters: {
            query?: never;
            header: {
                "X-Revalidate-Secret": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "/sekolah/bali/kab-badung/kuta-utara/negeri/smp-negeri-2-kuta-utara",
                     *       "/sekolah/bali/kab-badung/kuta-utara/"
                     *     ]
                     */
                    paths: string[];
                };
            };
        };
        responses: {
            /** @description Revalidation triggered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad secret. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
